### ISSUE TITLE
User Story 1: issues using aggregator endpoint

### ISSUE THREAD

**Issue by clausmichele** [openEOPlatform/SRR1_notebooks#5]
I'm collecting here issues I am facing updating the User Story 1 using the openEO Platform aggregator-

1. @jdries The following code was used to show the extent of four Landsat tiles hosted at EODC but it does not work anymore using the aggregator. It still works connecting directly to the EODC back-end:
```

import openeo
backend = "https://openeo.cloud"
conn = openeo.connect(backend).authenticate_oidc()
itemIter = conn.collection_items(
    "boa_landsat_8",
    temporal_extent = ["2019-09-20", "2019-09-21"],
    spatial_extent = [5.0,45.0,20.0,50.0]
)
next(itemIter)
```

**FOLLOWING ISSUE HAS BEEN SOLVED**
2. @christianbriese @sophieherrmann The jobs are not running with EODC through aggregator nor when directly connected. They return an error without any further detail. I've tried to run the following graph with geotiff or netcdf as output file format, I attach also the job ids:

EODC (Aggregator):
eodc-jb-5383d3bb-c653-4fbc-a506-686c4f6dab00
eodc-jb-ce8010d3-9942-4636-a5da-78922bc284e7

EODC:
jb-5b25d1d4-8ffc-478e-a7de-4a688e0ef1dd

PG:
```
{
  "process_graph": {
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "bands": [
          "B01",
          "B02",
          "B03"
        ],
        "id": "boa_landsat_8",
        "spatial_extent": {
          "west": 10.850372,
          "east": 10.947189,
          "south": 45.777892,
          "north": 45.831502,
          "crs": "EPSG:4326"
        },
        "temporal_extent": [
          "2019-09-20",
          "2019-09-21"
        ]
      }
    },
    "saveresult1": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "format": "netCDF",
        "options": {}
      },
      "result": true
    }
  }
}
```

**Comment by sophieherrmann** [comment]
In the given date range no data can be found, because the end date is excluded (so date rang is `2019-09-20` to `2019-09-20`). See API spec https://processes.openeo.org/#load_collection and implementation https://github.com/Open-EO/openeo-odc/blame/master/src/openeo_odc/map_processes_odc.py#L56.

using a temporal extent of `['2019-09-20', '2019-09-22']` produces the expected result. See job  `jb-28945d55-9ec3-403b-94c0-5f5750d0cbdf`.

We know that the current error message resulting from this error is insufficient and we are working on resolving this https://github.com/Open-EO/openeo-processes-python/issues/50
